
distribute:
  id:
    #工作机器ID
    work-id: 07
    #数据中心ID
    data-center-id: 01

spring:
  redis:
    host: 192.168.100.120
    database: 0
    port: 6379

logging:
  level:
    org.springboot.distribute: debug
    org.springframework.data.redis: debug